//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningPlan
    {
        public int PlanId { get; set; }
        public string Timeline { get; set; }
        public string Topics { get; set; }
        public Nullable<int> CLOId { get; set; }
        public Nullable<int> TeachingStrategieId { get; set; }
        public Nullable<int> AssessmentStrategieId { get; set; }
    
        public virtual AssessmentStrategie AssessmentStrategie { get; set; }
        public virtual CLO CLO { get; set; }
        public virtual TeachingStrategie TeachingStrategie { get; set; }
    }
}
